{"changes": {"state": {"new": "resolved", "old": "new"}}, "links": {"self": {"href": "data/repositories/osrf/srcsim/issues/222/changes/37417537.json"}, "html": {"href": "#!/osrf/srcsim/issues/222#comment-37417537"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/srcsim/issues/222.json"}}, "type": "issue", "id": 222, "repository": {"links": {"self": {"href": "data/repositories/osrf/srcsim.json"}, "html": {"href": "#!/osrf/srcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{c41021d9-0217-4628-999d-7f8d82f98dcb}ts=c_plus_plus"}}, "type": "repository", "name": "srcsim", "full_name": "osrf/srcsim", "uuid": "{c41021d9-0217-4628-999d-7f8d82f98dcb}"}, "title": "Local docker network error"}, "created_on": "2017-06-07T01:03:59.204820+00:00", "user": {"display_name": "Tom Tseemceeb Xiong", "uuid": "{07f3561e-974e-4e4d-962c-56f955baaac3}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B07f3561e-974e-4e4d-962c-56f955baaac3%7D"}, "html": {"href": "https://bitbucket.org/%7B07f3561e-974e-4e4d-962c-56f955baaac3%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/6aaf7437b4e057d91bcfca8bb6b456c9d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsTX-1.png"}}, "nickname": "Tom_Xiong", "type": "user", "account_id": "557058:5667b998-d71d-4e95-94f3-a06536d031b0"}, "message": {"raw": null, "markup": "markdown", "html": "", "type": "rendered"}, "type": "issue_change", "id": 37417537}