{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/srcsim.json"}, "html": {"href": "#!/osrf/srcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{c41021d9-0217-4628-999d-7f8d82f98dcb}ts=c_plus_plus"}}, "type": "repository", "name": "srcsim", "full_name": "osrf/srcsim", "uuid": "{c41021d9-0217-4628-999d-7f8d82f98dcb}"}, "links": {"attachments": {"href": "data/repositories/osrf/srcsim/issues/222/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/srcsim/issues/222.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/srcsim/issues/222/watch"}, "comments": {"href": "data/repositories/osrf/srcsim/issues/222/comments_page=1.json"}, "html": {"href": "#!/osrf/srcsim/issues/222/local-docker-network-error"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/srcsim/issues/222/vote"}}, "reporter": {"display_name": "Tom Tseemceeb Xiong", "uuid": "{07f3561e-974e-4e4d-962c-56f955baaac3}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B07f3561e-974e-4e4d-962c-56f955baaac3%7D"}, "html": {"href": "https://bitbucket.org/%7B07f3561e-974e-4e4d-962c-56f955baaac3%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/6aaf7437b4e057d91bcfca8bb6b456c9d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsTX-1.png"}}, "nickname": "Tom_Xiong", "type": "user", "account_id": "557058:5667b998-d71d-4e95-94f3-a06536d031b0"}, "title": "Local docker network error", "component": null, "votes": 0, "watches": 1, "content": {"raw": "After performing the image build:\r\n\r\n```\r\n#!\r\n\r\ndocker build -t fcomputer:latest <github_url>\r\n```\r\nI then run the bash script:\r\n```\r\n#!\r\n\r\n./fc_run_team_docker.bash\r\n```\r\nWhich gives me this error:\r\n\r\n```\r\n#!\r\n\r\ndocker: Error response from daemon: network vpn-br0 not found.\r\n```\r\nNot really sure what to do with this so I'm pretty much stumped.", "markup": "markdown", "html": "<p>After performing the image build:</p>\n<div class=\"codehilite\"><pre><span></span>docker build -t fcomputer:latest &lt;github_url&gt;\n</pre></div>\n\n\n<p>I then run the bash script:</p>\n<div class=\"codehilite\"><pre><span></span>./fc_run_team_docker.bash\n</pre></div>\n\n\n<p>Which gives me this error:</p>\n<div class=\"codehilite\"><pre><span></span><span class=\"n\">docker</span><span class=\"o\">:</span> <span class=\"n\">Error</span> <span class=\"n\">response</span> <span class=\"n\">from</span> <span class=\"n\">daemon</span><span class=\"o\">:</span> <span class=\"n\">network</span> <span class=\"n\">vpn</span><span class=\"o\">-</span><span class=\"n\">br0</span> <span class=\"n\">not</span> <span class=\"n\">found</span><span class=\"o\">.</span>\n</pre></div>\n\n\n<p>Not really sure what to do with this so I'm pretty much stumped.</p>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2017-06-06T04:39:17.851274+00:00", "milestone": null, "updated_on": "2017-06-07T01:03:59.184899+00:00", "type": "issue", "id": 222}